/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SHS;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class confirmpayment extends javax.swing.JFrame {

    /**
     * Creates new form confirmpayment
     */
    public confirmpayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ctlab1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctlab2 = new javax.swing.JLabel();
        ctlab3 = new javax.swing.JLabel();
        sbut1 = new javax.swing.JButton();
        sbut = new javax.swing.JButton();
        ctlab4 = new javax.swing.JLabel();
        CNTXTaa = new javax.swing.JTextField();
        eatxt = new javax.swing.JTextField();
        cntxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 242, 197));

        jLabel1.setFont(new java.awt.Font("Hobo Std", 1, 18)); // NOI18N
        jLabel1.setText("PAYMENT");

        ctlab1.setFont(new java.awt.Font("Hiragino Sans GB", 1, 16)); // NOI18N
        ctlab1.setText("Card Number :");

        jLabel2.setText("jLabel2");

        ctlab2.setFont(new java.awt.Font("Hiragino Sans GB", 1, 16)); // NOI18N
        ctlab2.setText("Total Payable Amount : ");

        ctlab3.setFont(new java.awt.Font("Hiragino Sans GB", 1, 16)); // NOI18N
        ctlab3.setText("Email Address :");

        sbut1.setText("Cancel");
        sbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbut1ActionPerformed(evt);
            }
        });

        sbut.setText("Submit");
        sbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbutActionPerformed(evt);
            }
        });

        ctlab4.setFont(new java.awt.Font("Hiragino Sans GB", 1, 16)); // NOI18N
        ctlab4.setText("Contact Number : ");

        CNTXTaa.setText("jTextField1");

        eatxt.setText("jTextField1");

        cntxt.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ctlab3)
                                .addGap(18, 18, 18)
                                .addComponent(eatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ctlab1)
                                .addGap(18, 18, 18)
                                .addComponent(CNTXTaa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ctlab4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(sbut1)
                        .addGap(76, 76, 76)
                        .addComponent(sbut)))
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(ctlab2)
                    .addContainerGap(376, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctlab1)
                    .addComponent(CNTXTaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctlab3)
                    .addComponent(eatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctlab4)
                    .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbut1)
                    .addComponent(sbut))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(ctlab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(228, 228, 228)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbut1ActionPerformed
        JOptionPane.showMessageDialog(null,"Process Terminated" , "Error",JOptionPane.ERROR_MESSAGE,null);
        payment p= new payment();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_sbut1ActionPerformed

    private void sbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbutActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are You Confirm Make Payment?", "Confirmation",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null);
        if (result==JOptionPane.YES_OPTION){
            String contact;
            String card;
            String address;

            card = CNTXTaa.getText();
            contact = cntxt.getText();
            address = eatxt.getText();

            if( CNTXTaa.getText().isEmpty() || cntxt.getText().isEmpty() || eatxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Text Field Cannot Be Empty!" , "TextField Empty",JOptionPane.ERROR_MESSAGE,null);
            }else{

                Child c = new Child(contact,card,address);

                JOptionPane.showMessageDialog(this,"Contact is :"+ c.getcontact()+"\n"+"Card Number is :"+ c.getcard()+"\n"+"Address is :"+ c.getaddress());
                JOptionPane.showMessageDialog(null,"Payment Successful" , "Payment",JOptionPane.PLAIN_MESSAGE,null);

                
    }//GEN-LAST:event_sbutActionPerformed
        }}
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNTXTaa;
    private javax.swing.JTextField cntxt;
    private javax.swing.JLabel ctlab1;
    private javax.swing.JLabel ctlab2;
    private javax.swing.JLabel ctlab3;
    private javax.swing.JLabel ctlab4;
    private javax.swing.JTextField eatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sbut;
    private javax.swing.JButton sbut1;
    // End of variables declaration//GEN-END:variables
}
